// Generated by breel.build.ClosureDevelopmentPhase

goog.addDependency("../jomv3/main.js", ["jomv3.main"], ["goog.userAgent.product","jomv3.App","jomv3.Utils"]);
  goog.addDependency("../jomv3/App.js", ["jomv3.App"], ["goog.events","goog.userAgent","goog.math","goog.window","jomv3.controllers.AssetsController","jomv3.controllers.NavigationController","jomv3.views.elements.RoundThumb","jomv3.views.elements.UISpinner","jomv3.fx.FermatSpiral","jomv3.fx.CssScrollBar","jomv3.fx.DefaultScrollBar","jomv3.fx.ScrollableElement","jomv3.fx.Scroller"]);
    goog.addDependency("../jomv3/controllers/AssetsController.js", ["jomv3.controllers.AssetsController"], ["goog.array","goog.dom","goog.events.EventTarget","goog.events","goog.History","goog.object"]);
    goog.addDependency("../jomv3/controllers/NavigationController.js", ["jomv3.controllers.NavigationController"], ["goog.array","goog.dom","goog.events.EventTarget","goog.events","goog.History","goog.object","goog.string"]);
    goog.addDependency("../jomv3/views/elements/RoundThumb.js", ["jomv3.views.elements.RoundThumb"], ["goog.dom","goog.events.EventTarget","goog.fx","goog.style"]);
    goog.addDependency("../jomv3/views/elements/UISpinner.js", ["jomv3.views.elements.UISpinner"], ["goog.dom","goog.events.EventTarget","goog.style"]);
    goog.addDependency("../jomv3/fx/FermatSpiral.js", ["jomv3.fx.FermatSpiral"], []);
    goog.addDependency("../jomv3/fx/CssScrollBar.js", ["jomv3.fx.CssScrollBar"], ["goog.fx.dom.Slide","goog.fx.easing","goog.fx.Animation","goog.style","jomv3.fx.DummyScrollBar"]);
      goog.addDependency("../jomv3/fx/DummyScrollBar.js", ["jomv3.fx.DummyScrollBarManager","jomv3.fx.DummyScrollBar"], ["goog.array","goog.events.EventType","goog.events.MouseWheelHandler","goog.dom","goog.dom.ViewportSizeMonitor","goog.userAgent","goog.dom","goog.dom.classes","goog.events.EventTarget","goog.events.MouseWheelHandler","goog.fx.anim","goog.fx.Dragger","goog.math.Size","goog.math.Rect","goog.style"]);
    goog.addDependency("../jomv3/fx/DefaultScrollBar.js", ["jomv3.fx.DefaultScrollBar"], ["jomv3.fx.DummyScrollBar"]);
    goog.addDependency("../jomv3/fx/ScrollableElement.js", ["jomv3.fx.ScrollableElementManager","jomv3.fx.ScrollableElement"], ["goog.array","goog.events.EventType","goog.dom","goog.userAgent","goog.dom","goog.events","goog.math","goog.userAgent"]);
    goog.addDependency("../jomv3/fx/Scroller.js", ["jomv3.fx.Scroller"], ["goog.array","goog.dom","goog.events","goog.userAgent","jomv3.fx.ScrollableElement","jomv3.fx.DefaultScrollBar","jomv3.fx.CssScrollBar"]);
  goog.addDependency("../jomv3/utils.js", ["jomv3.Utils"], ["goog.dom","goog.dom.classes","goog.fx.css3","goog.fx.Transition","goog.style","goog.style.cursor","goog.userAgent","goog.math"]);

goog.require('jomv3.main');