// Generated by breel.build.ClosureDevelopmentPhase

goog.addDependency("../jomv3/App.js", ["jomv3.App"], []);
goog.addDependency("../jomv3/build/DevelopmentBuilder.js", ["jomv3.DevelopmentBuilder"], ["breel.build.Builder","breel.build.ClosureDevelopmentPhase"]);
goog.addDependency("../jomv3/build/ReleaseBuilder.js", ["jomv3.ReleaseBuilder"], ["breel.build.Builder"]);
goog.addDependency("../jomv3/main.js", ["jomv3.main"], ["jomv3.App"]);

goog.require('jomv3.main');